name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - uses: actions/checkout@v4
      - run: ./gradlew build javadocJar checkMappings --stacktrace --warning-mode fail
      - run: ./gradlew formatMappings --stacktrace --warning-mode fail
      - name: Check mapping format
        run: |
          git add -A
          git status
          if [ -n "$(git status --porcelain)" ]; then exit 1; fi
      - name: Build artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

  test-build-logic:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - run: ./gradlew :filament:build
